### Create user

POST http://localhost:5000/auth/signup
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "qwerty123",
  "username" : "Diana"
}

### Login

POST http://localhost:5000/auth/signin
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "qwerty123",
  "username" : "Diana"
}

### Logout

POST http://localhost:5000/auth/logout
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YjY1N2FjZTFlZDRlNzBmYjIwNjMwZWMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInVzZXJuYW1lIjoiRGlhbmEiLCJpYXQiOjE1MzMzNzcyMzcsImV4cCI6MTUzMzM5ODgzN30.afpiyPpCTkSjHEEE74aUwPTs_tv9XoP9axw_eHZaroo

### Add event
POST http://localhost:5000/events
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YjY1N2FjZTFlZDRlNzBmYjIwNjMwZWMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInVzZXJuYW1lIjoiRGlhbmEiLCJpYXQiOjE1MzMzNzcyMzcsImV4cCI6MTUzMzM5ODgzN30.afpiyPpCTkSjHEEE74aUwPTs_tv9XoP9axw_eHZaroo

{
  "start": 250,
  "duration": 105,
  "title" : "Daily meeting4"
}

### Delete event
DELETE http://localhost:5000/events/5b657be00f709511f4ee2e0b
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YjY1N2FjZTFlZDRlNzBmYjIwNjMwZWMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInVzZXJuYW1lIjoiRGlhbmEiLCJpYXQiOjE1MzMzNzcyMzcsImV4cCI6MTUzMzM5ODgzN30.afpiyPpCTkSjHEEE74aUwPTs_tv9XoP9axw_eHZaroo

### Get event
GET http://localhost:5000/events/5b6580405f96961933fd9510
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YjY1N2FjZTFlZDRlNzBmYjIwNjMwZWMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInVzZXJuYW1lIjoiRGlhbmEiLCJpYXQiOjE1MzMzNzcyMzcsImV4cCI6MTUzMzM5ODgzN30.afpiyPpCTkSjHEEE74aUwPTs_tv9XoP9axw_eHZaroo

### Get all events of user
GET http://localhost:5000/events
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YjY1N2FjZTFlZDRlNzBmYjIwNjMwZWMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInVzZXJuYW1lIjoiRGlhbmEiLCJpYXQiOjE1MzMzNzcyMzcsImV4cCI6MTUzMzM5ODgzN30.afpiyPpCTkSjHEEE74aUwPTs_tv9XoP9axw_eHZaroo

###





